### ISSUE TITLE
How to change read more/read less text color ?

### ISSUE THREAD

**Issue by madHorse54** [hazrat84/read-more#2]

**Comment by hazrat84** [comment]
In your global css file try something like this
a.text-primary {
      color: YOUR_COLOR !important;
    }
or you can make it more specific so that it does not effect other links
app-read-more p small a.text-primary {
    color: YOUR_COLOR !important;
}

**Comment by hazrat84** [comment]
> _No description provided._

In your global css file try something like this
a.text-primary {
color: YOUR_COLOR !important;
}
or you can make it more specific so that it does not effect other links
app-read-more p small a.text-primary {
color: YOUR_COLOR !important;
}

**Comment by hazrat84** [comment]
"In your global css file try something like this
a.text-primary {
color: YOUR_COLOR !important;
}
or you can make it more specific so that it does not effect other links
app-read-more p small a.text-primary {
color: YOUR_COLOR !important;
}"

**Comment by madHorse54** [comment]
> @madHorse54
> In your global css file try something like this
> a.text-primary {
> color: YOUR_COLOR !important;
> }
> or you can make it more specific so that it does not effect other links
> app-read-more p small a.text-primary {
> color: YOUR_COLOR !important;
> }

@hazrat84 
OK. It's working. Thx

**Comment by madHorse54** [comment]
@hazrat84 
Perfect. It's working.
thanks

**Comment by allisonaung** [comment]
I got item in *ngfor. 
```
 <tr *ngFor="let item of shoppingDetails.casualPayment>
<td>  {{ item.refundReasonText }}

  
</td>
 
</tr>
```

So I tried this
```
 <tr *ngFor="let item of shoppingDetails.casualPayment>
<td> <app-read-more [text]='refundReasonText' maxLength="10"></app-read-more>

  
</td>
 
</tr>
```
It doesn't work.
Can you help me?
Cheers,

**Comment by hazrat84** [comment]
@allisonaung  maxLength should be in brakets like [maxLength]="10"
